# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` 

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [2]:
np.__version__

'1.26.4'

#### 3. Create a null vector of size 10

In [3]:
null_a=np.zeros(10)
null_a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array 

In [4]:
null_a.nbytes

80




#### 5. How to get the documentation of the numpy add function from the command line?

In [5]:
# %run `python -c "import numpy; numpy.info(numpy.add)"`

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [10]:
null_10 = np.zeros(10)
null_10[4] = 1
null_10

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49

In [11]:
rag_v = np.arange(10,50)
rag_v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last)

In [42]:
a = np.arange(10)
a
b=a[::-1]
print(a,b)


[0 1 2 3 4 5 6 7 8 9] [9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [20]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [21]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix

In [22]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [23]:
np.random.random((3,3,3))

array([[[0.12363573, 0.2339873 , 0.85871072],
        [0.34211874, 0.06799054, 0.02652245],
        [0.51861432, 0.15160473, 0.54296081]],

       [[0.54456652, 0.73088315, 0.85742168],
        [0.08117778, 0.88967141, 0.22645259],
        [0.51762872, 0.8821885 , 0.34835836]],

       [[0.04797766, 0.23425321, 0.26877674],
        [0.93779908, 0.3456818 , 0.98212376],
        [0.82643734, 0.84593699, 0.46499901]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
a=np.random.random((10,10))
print(a.min(),a.max())


0.007338921717459201 0.9948934377165963


#### 14. Create a random vector of size 30 and find the mean value

In [29]:
a = np.random.random(30)
print(a.mean())

0.5615993432135381


#### 15. Create a 2d array with 1 on the border and 0 inside

In [31]:
a=np.ones((10,10))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

#### 16. How to add a border (filled with 0's) around an existing array?

In [36]:
a = np.ones((5,5))
a[:, [0, -1]] = 0
a[[0, -1], :] = 0
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [46]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [47]:
a = np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [48]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [51]:
a=np.unravel_index(99,(6,7,8))
a

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function

In [52]:
a=np.tile( np.array([[0,1],[1,0]]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix

In [53]:
a=np.random.random((5,5))
a = (a - np.mean (a)) / (np.std (a))
print(a)

[[ 0.05172086  0.5136365   1.22881707  1.08928988  1.24874244]
 [-1.37901494 -0.09965029  0.08481202  1.17534513 -0.83132185]
 [ 0.37055739  0.3868275   0.4795521  -1.81121973 -1.70370399]
 [ 1.44776157  0.29904019 -1.827011   -1.45929078 -0.25169043]
 [ 0.99570017  0.76835136 -0.49555271  0.17766533 -0.45936377]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [57]:
color_dtype = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color = np.array((255, 128, 0, 255), dtype=color_dtype)
print(color)
                  

(255, 128, 0, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [59]:
a=np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [61]:
a=np.arange(11)
a[(a > 3) & (a < 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [62]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [63]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [64]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\hp\AppData\Local\Temp\ipykernel_25056\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\hp\AppData\Local\Temp\ipykernel_25056\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\hp\AppData\Local\Temp\ipykernel_25056\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ?

In [66]:
a = np.random.uniform(-10,+10,10)
a

array([ 4.75369381,  4.92229184,  6.33842448,  0.27690243,  3.86801698,
        1.6128047 ,  6.70115092,  7.29464157, -8.91808553, -7.64088401])

#### 30. How to find common values between two arrays?

In [68]:
a=np.random.randint(0,10,10)
b=np.random.randint(0,10,10)
print(a,b,np.intersect1d(a,b))

[9 2 1 7 0 2 1 4 5 5] [8 6 6 5 5 7 0 2 5 2] [0 2 5 7]


#### 31. How to ignore all numpy warnings (not recommended)?

In [69]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [70]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\hp\AppData\Local\Temp\ipykernel_25056\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow?

In [73]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today= np.datetime64('today')
tomorrow=np.datetime64('today') + np.timedelta64(1)

print(yesterday,today,tomorrow)



2024-07-04 2024-07-05 2024-07-06


#### 34. How to get all the dates corresponding to the month of July 2016?

In [74]:
date = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
date

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [75]:
a=np.ones(3)*1
b=np.ones(3)*2
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)
print(a)

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [76]:
a=np.random.uniform(0,10,10)

print (a - a%1)
print (np.floor(a))
print (np.ceil(a)-1)
print (a.astype(int))
print (np.trunc(a))

[6. 5. 9. 7. 3. 1. 4. 0. 7. 5.]
[6. 5. 9. 7. 3. 1. 4. 0. 7. 5.]
[6. 5. 9. 7. 3. 1. 4. 0. 7. 5.]
[6 5 9 7 3 1 4 0 7 5]
[6. 5. 9. 7. 3. 1. 4. 0. 7. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [77]:
a=np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array

In [78]:
a=np.tile(np.arange(0, 5), (5, 1))
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [80]:
a=np.random.random((3,3))
a = np.linspace(0, 1, 12)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it

In [83]:
a=np.random.rand((10))
np.sort(a)


array([0.17468912, 0.41184843, 0.49165698, 0.51468832, 0.51750922,
       0.54110681, 0.59043396, 0.60134901, 0.84397222, 0.95458212])

#### 41. How to sum a small array faster than np.sum?

In [88]:
a = np.array([1, 2, 3, 4, 5])
sum_result = sum(array)
print(sum_result)
a

<built-in function array>


array([1, 2, 3, 4, 5])

#### 42. Consider two random array A and B, check if they are equal

In [90]:
a=np.array([1,2,3,4,5]) 
b=np.array([1,2,7,4,5])
print(a==b)

[ True  True False  True  True]


#### 43. Make an array immutable (read-only) 

In [92]:
a=np.array([1,2,3,4,5])
immutable_a = np.array(a, copy=False)

print(immutable_a)

[1 2 3 4 5]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [95]:
import numpy as np
matrix = np.random.random((10, 2))
x = matrix[:, 0]
y = matrix[:, 1]
radius = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar_matrix = np.vstack((radius, theta)).T

print(f"Original Matrix (Cartesian):\n{matrix}")
print(f"\nPolar Matrix:\n{polar_matrix}")


Original Matrix (Cartesian):
[[0.07846824 0.46645456]
 [0.74606699 0.77216695]
 [0.78784683 0.05904799]
 [0.59446908 0.41245659]
 [0.6593957  0.49845892]
 [0.8959241  0.2676923 ]
 [0.71889443 0.36510865]
 [0.42376724 0.46786994]
 [0.97037686 0.84333025]
 [0.31751618 0.3754001 ]]

Polar Matrix:
[[0.47300858 1.40413407]
 [1.07371214 0.80258747]
 [0.79005652 0.0748087 ]
 [0.72354262 0.60656859]
 [0.82659784 0.64728738]
 [0.93506104 0.29034545]
 [0.80629617 0.4699279 ]
 [0.63125348 0.83482049]
 [1.28562714 0.71546437]
 [0.49167241 0.86874133]]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [96]:
a=np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.63859597 0.15906592 0.20649887 0.         0.06487192 0.85124437
 0.14643462 0.75497873 0.59047513 0.40604172]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [97]:
n = 5
x = np.linspace(0, 1, n)
y = np.linspace(0, 1, n)
X, Y = np.meshgrid(x, y)

structured_array = np.empty(X.shape, dtype=[('x', float), ('y', float)])
structured_array['x'] = X
structured_array['y'] = Y

print(structured_array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [99]:
X = np.array([1, 2, 3])
Y = np.array([4, 5])
C = 1 / (X[:, np.newaxis] - Y)

print(C)

[[-0.33333333 -0.25      ]
 [-0.5        -0.33333333]
 [-1.         -0.5       ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type

In [103]:
int_types = [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64]
float_types = [np.float16, np.float32, np.float64]
print("Integer Types:")
for dtype in int_types:
  info = np.iinfo(dtype) 
  print(f"{dtype.__name__}: min = {info.min}, max = {info.max}")


print("\nFloating-Point Types:")
for dtype in float_types:
  info = np.finfo(dtype)  # Get information for floating-point data types
  print(f"{dtype.__name__}: min = {info.min}, max = {info.max}")


Integer Types:
int8: min = -128, max = 127
int16: min = -32768, max = 32767
int32: min = -2147483648, max = 2147483647
int64: min = -9223372036854775808, max = 9223372036854775807
uint8: min = 0, max = 255
uint16: min = 0, max = 65535
uint32: min = 0, max = 4294967295
uint64: min = 0, max = 18446744073709551615

Floating-Point Types:
float16: min = -65504.0, max = 65504.0
float32: min = -3.4028234663852886e+38, max = 3.4028234663852886e+38
float64: min = -1.7976931348623157e+308, max = 1.7976931348623157e+308


#### 49. How to print all the values of an array? 

In [106]:
a=np.array([1, 2, 3, 4, 5])
for value in a:
    print(a)

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


#### 50. How to find the closest value (to a given scalar) in a vector?

In [107]:
vector = np.array([1, 3, 5, 7, 9])
scalar = 4
difference = np.abs(vector - scalar)
index = np.argmin(difference)
closest_value = vector[index]

print(closest_value)

3


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [108]:
dtype = np.dtype([('x', np.float64), ('y', np.float64), ('r', np.uint8), ('g', np.uint8), ('b', np.uint8)])

data = np.array([(1.0, 2.0, 255, 0, 0), (3.0, 4.0, 0, 255, 0), (5.0, 6.0, 0, 0, 255)], dtype=dtype)

print(data)

[(1., 2., 255,   0,   0) (3., 4.,   0, 255,   0) (5., 6.,   0,   0, 255)]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [109]:
np.random.seed(0)
coordinates = np.random.rand(100, 2)
distances = np.zeros((100, 100))
for i in range(100):
    for j in range(100):
        distances[i, j] = np.sqrt(np.sum((coordinates[i] - coordinates[j])**2))
print(distances.shape) 
print(distances)


(100, 100)
[[0.         0.1786471  0.14306129 ... 0.29476183 0.56184    0.5654225 ]
 [0.1786471  0.         0.20562852 ... 0.14721688 0.47464981 0.55582212]
 [0.14306129 0.20562852 0.         ... 0.35206592 0.43796338 0.42237997]
 ...
 [0.29476183 0.14721688 0.35206592 ... 0.         0.5639395  0.68382195]
 [0.56184    0.47464981 0.43796338 ... 0.5639395  0.         0.24721062]
 [0.5654225  0.55582212 0.42237997 ... 0.68382195 0.24721062 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [7]:
float = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0], dtype=np.float32)
int = float.view(dtype=np.int32)
int

array([1065353216, 1073741824, 1077936128, 1082130432, 1084227584,
       1086324736, 1088421888, 1090519040, 1091567616, 1092616192])

#### 54. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays?

#### 56. Generate a generic 2D Gaussian-like array

#### 57. How to randomly place p elements in a 2D array?

#### 58. Subtract the mean of each row of a matrix

#### 59. How to sort an array by the nth column?

#### 60. How to tell if a given 2D array has null columns?

#### 61. Find the nearest value from a given value in an array

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

#### 63. Create an array class that has a name attribute

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

#### 69. How to get the diagonal of a dot product?

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

#### 72. How to swap two rows of an array?

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

#### 75. How to compute averages using a sliding window over an array?

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

#### 77. How to negate a boolean, or to change the sign of a float inplace?

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 

#### 88. How to implement the Game of Life using numpy arrays?

#### 89. How to get the n largest values of an array

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 

#### 91. How to create a record array from a regular array?

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

#### 95. Convert a vector of ints into a matrix binary representation

#### 96. Given a two dimensional array, how to extract unique rows?

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).